version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network
  db:
    image: postgres:14.11
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  pgdata:
