version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network
  db:
    image: postgres:14.11
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  pgdata:
